### ISSUE TITLE
Module NotFoundError: No module named 'gdal'  for QGIS : 3.18.3-Zürich Zürich

### ISSUE THREAD

**Issue by CvenTito** [geocledian/agknow_qgis3#7]
Hello everyone,
It seems to appear an error concerning the installation and the call to its method classFactory() of the plugins
Any solutions?
Thanks

Impossible de charger l'extension 'agknow_qgis' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/.../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/agknow_qgis/__init__.py", line 34, in classFactory
    from .agknow_qgis import Agknow
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/.../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/agknow_qgis/agknow_qgis.py", line 32, in 
    from .agknow_qgis_dockwidget import AgknowDockWidget
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/.../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/agknow_qgis/agknow_qgis_dockwidget.py", line 37, in 
    from .agknow_worker import *
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/.../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/agknow_qgis/agknow_worker.py", line 32, in 
    from . import agknow_utils
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/.../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/agknow_qgis/agknow_utils.py", line 29, in 
    import gdal, osr
  File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

**Comment by myxBeni** [comment]
might be this here: https://gis.stackexchange.com/a/413822/203521

**Comment by gc-sommer** [comment]
Hi @CvenTito and @myxBeni,

Sorry for the delay! We will fix this - but we have to work on the migration of the plugin to our API v4 backend. At the moment this plugin is still for API v3 only.

Best regards,
Johannes

**Comment by gc-sommer** [comment]
fixed with 0.7.4 release
